### ISSUE TITLE
[FEAT] UI 개선 및 템플릿 리팩토링 작업

### ISSUE THREAD

**Issue by hyeonjeong-ko** [hyeonjeong-ko/Catch-Goorm#1]
## Background
- 사용자 인터페이스(UI)를 개선하여 각 페이지(로그인, 홈, 회원가입, 정보 수정, 계정 삭제)의 디자인을 일관되게 만들고, 버튼 위치 및 색상 조정
- 중복된 코드와 스타일을 제거하고, 유지보수를 쉽게 하기 위해 템플릿을 재구성하는 것이 목표

## Todo
- [x] `base.html` 작성 및 각 페이지에서 중복 코드 제거
- [x] 홈 페이지에서 로그아웃 버튼의 색상 및 위치 조정
- [x] 모든 버튼과 폼의 스타일 통일

## See also
- [Django Template Documentation](https://docs.djangoproject.com/en/stable/ref/templates/)
