### ISSUE TITLE
[FEAT] 프로필 업데이트 및 수정 기능 추가

### ISSUE THREAD

**Issue by hyeonjeong-ko** [hyeonjeong-ko/Catch-Goorm#3]
## Background
- 사용자가 자신의 프로필 정보를 수정할 수 있도록 하기 위해 프로필 업데이트 기능을 구현
- 프로필 이미지, 이름, 비밀번호를 사용자가 직접 업데이트할 수 있어야 함
- 사용자 경험을 향상시키기 위해 프로필 이미지를 클릭하면 새로운 이미지를 업로드할 수 있도록 추가

## Todo
- [x] 프로필 이미지  파일 업로드 & 수정 기능 추가
- [x] 프로필 이미지 클릭 시 파일 선택 창을 자동으로 열기
- [x] 파일 업로드 시 미리보기 기능 구현 (JavaScript)
- [x] 이에맞게 front 수정

## See also
- Django 공식 문서: https://docs.djangoproject.com/en/stable/topics/files/
- FileReader API (JavaScript): https://developer.mozilla.org/en-US/docs/Web/API/FileReader
